-- Release v0.1.2: keep system_information aligned with the running build,
-- so /api/system and the About page report the correct version.
-- Generated by scripts/release.sh.
UPDATE system_information
SET version     = '0.1.2',
    released_at = CURRENT_DATE,
    modified_at = now()
WHERE id = 1;
