package beer.thierry.centsible.jooq.repository

import beer.thierry.centsible.api.model.category.CategoryDTO
import beer.thierry.centsible.api.model.category.CategoryForm
import beer.thierry.centsible.api.model.category.CategoryType
import beer.thierry.centsible.api.model.user.UserDTO
import beer.thierry.centsible.api.repository.CategoryClassification
import beer.thierry.centsible.api.repository.ICategoriesRepository
import beer.thierry.jooq.generated.tables.references.ACCOUNTS
import beer.thierry.jooq.generated.tables.references.CATEGORIES
import beer.thierry.jooq.generated.tables.references.TRANSACTIONS
import org.jooq.DSLContext
import org.jooq.Field
import org.jooq.Record
import org.jooq.impl.DSL
import org.springframework.stereotype.Repository
import java.time.OffsetDateTime

@Repository
class CategoriesRepository(private val dsl: DSLContext) : ICategoriesRepository {

    // Migration 28 adds `system_key` to `categories`. The jOOQ-generated reference
    // is regenerated by `:centsible-jooq:jooqCodegen`; until that runs the column
    // is reachable via a raw field reference. Swap this for `CATEGORIES.SYSTEM_KEY`
    // after the next codegen.
    private val systemKey: Field<String?> = DSL.field(DSL.name("system_key"), String::class.java)

    private val categoryProjection: Array<Field<*>> = arrayOf(
        CATEGORIES.ID,
        CATEGORIES.NAME,
        CATEGORIES.ICON,
        CATEGORIES.COLOR,
        CATEGORIES.TYPE,
        CATEGORIES.USER_ID,
        systemKey,
    )

    override fun fetchAllCategories(authenticatedUser: UserDTO): List<CategoryDTO> {
        return dsl.select(*categoryProjection)
            .from(CATEGORIES)
            .where(CATEGORIES.USER_ID.eq(authenticatedUser.id).or(CATEGORIES.USER_ID.isNull))
            .and(CATEGORIES.IS_MANAGED.isFalse)
            .fetch { mapCategory(it) }
    }

    override fun fetchCategoryById(authenticatedUser: UserDTO, id: Long): CategoryDTO? {
        return dsl.select(*categoryProjection)
            .from(CATEGORIES)
            .where(
                (CATEGORIES.USER_ID.eq(authenticatedUser.id).or(CATEGORIES.USER_ID.isNull))
                    .and(CATEGORIES.ID.eq(id))
                    .and(CATEGORIES.IS_MANAGED.isFalse)
            )
            .fetchOne { mapCategory(it) }
    }

    override fun fetchSystemCategoryByKey(systemKey: String): CategoryDTO? =
        dsl.select(*categoryProjection)
            .from(CATEGORIES)
            .where(CATEGORIES.USER_ID.isNull.and(this.systemKey.eq(systemKey)))
            .fetchOne { mapCategory(it) }

    override fun fetchCategoryClassifications(
        authenticatedUser: UserDTO,
        ids: Collection<Long>,
    ): Map<Long, CategoryClassification> {
        if (ids.isEmpty()) return emptyMap()
        return dsl.select(CATEGORIES.ID, CATEGORIES.TYPE, CATEGORIES.IS_MANAGED)
            .from(CATEGORIES)
            .where(
                (CATEGORIES.USER_ID.eq(authenticatedUser.id).or(CATEGORIES.USER_ID.isNull))
                    .and(CATEGORIES.ID.`in`(ids))
            )
            .fetch { record ->
                record[CATEGORIES.ID]!! to CategoryClassification(
                    type = CategoryType.fromValue(record[CATEGORIES.TYPE]!!),
                    isManaged = record[CATEGORIES.IS_MANAGED] ?: false,
                )
            }
            .toMap()
    }

    override fun createCategory(authenticatedUser: UserDTO, category: CategoryForm): CategoryDTO {
        val record = dsl.insertInto(CATEGORIES)
            .set(CATEGORIES.NAME, category.name)
            .set(CATEGORIES.ICON, category.icon)
            .set(CATEGORIES.COLOR, category.color)
            .set(CATEGORIES.TYPE, category.type.value)
            .set(CATEGORIES.USER_ID, authenticatedUser.id)
            .set(CATEGORIES.CREATED_AT, OffsetDateTime.now())
            .returning(*categoryProjection)
            .fetchOne() ?: throw IllegalStateException("Failed to retrieve generated Category")

        return mapCategory(record)
    }

    override fun updateCategory(authenticatedUser: UserDTO, id: Long, category: CategoryForm): CategoryDTO? {
        val record = dsl.update(CATEGORIES)
            .set(CATEGORIES.NAME, category.name)
            .set(CATEGORIES.ICON, category.icon)
            .set(CATEGORIES.COLOR, category.color)
            .set(CATEGORIES.TYPE, category.type.value)
            .where(CATEGORIES.USER_ID.eq(authenticatedUser.id).and(CATEGORIES.ID.eq(id)))
            .returning(*categoryProjection)
            .fetchOne()

        return record?.let { mapCategory(it) }
    }

    override fun deleteCategory(authenticatedUser: UserDTO, id: Long): Boolean {
        return dsl.deleteFrom(CATEGORIES)
            .where(CATEGORIES.USER_ID.eq(authenticatedUser.id).and(CATEGORIES.ID.eq(id)))
            .execute() > 0
    }

    override fun isCategoryUsed(authenticatedUser: UserDTO, id: Long): Boolean {
        return dsl.fetchExists(
            dsl.selectOne()
                .from(TRANSACTIONS)
                .join(ACCOUNTS).on(ACCOUNTS.ID.eq(TRANSACTIONS.ACCOUNT_ID))
                .where(TRANSACTIONS.CATEGORY_ID.eq(id))
                .and(ACCOUNTS.USER_ID.eq(authenticatedUser.id))
        )
    }

    private fun mapCategory(record: Record) = CategoryDTO(
        id = record[CATEGORIES.ID],
        name = record[CATEGORIES.NAME],
        icon = record[CATEGORIES.ICON],
        color = record[CATEGORIES.COLOR],
        type = CategoryType.fromValue(record[CATEGORIES.TYPE]!!),
        isSystem = record[CATEGORIES.USER_ID] == null,
        systemKey = record[systemKey],
    )
}
