#!/usr/bin/env bash
# Cut a release of Centsible.
#
# Usage:   scripts/release.sh <version>
# Example: scripts/release.sh 0.2.0
#
# What this does, in order:
#   1. Validates semver, clean working tree, and that releases/<version> + v<version>
#      do not already exist.
#   2. Forks branch  releases/<version>  off the current HEAD.
#   3. Bumps  build.gradle.kts                     ->  version = "<version>"
#   4. Bumps  centsible-ui/package.json       ->  "version": "<version>"
#      (inserts the field after "name" if absent).
#   5. Writes centsible-db/migrations/NN_SetVersion_<slug>.sql, which
#      updates system_information.version + released_at so /api/system and the
#      About page report the running build.
#   6. Commits as  chore(release): v<version>  and creates annotated tag v<version>.
#
# After the script finishes:
#   - Edit CHANGELOG.md and amend the release commit (or add a follow-up).
#   - git push -u origin releases/<version>
#   - git push origin v<version>
#   - Open PR  releases/<version> -> main.

set -euo pipefail

VERSION="${1:-}"

if [[ -z "$VERSION" ]]; then
  echo "Usage: $0 <version>" >&2
  exit 2
fi

# Strict semver MAJOR.MINOR.PATCH with optional -prerelease.
if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?$ ]]; then
  echo "Error: '$VERSION' is not valid semver (MAJOR.MINOR.PATCH[-PRERELEASE])." >&2
  exit 2
fi

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

if ! git diff --quiet || ! git diff --cached --quiet; then
  echo "Error: working tree is not clean. Commit or stash changes before releasing." >&2
  exit 1
fi

BRANCH="releases/${VERSION}"
TAG="v${VERSION}"

if git show-ref --verify --quiet "refs/heads/${BRANCH}"; then
  echo "Error: branch ${BRANCH} already exists." >&2
  exit 1
fi
if git show-ref --verify --quiet "refs/tags/${TAG}"; then
  echo "Error: tag ${TAG} already exists." >&2
  exit 1
fi

CURRENT_VERSION="$(grep -E '^\s*version\s*=\s*"' build.gradle.kts | head -1 | sed -E 's/.*"([^"]+)".*/\1/')"
SOURCE_REF="$(git rev-parse --abbrev-ref HEAD)"

echo "Cutting v${VERSION} from ${SOURCE_REF} (currently ${CURRENT_VERSION})."
echo

git switch -c "${BRANCH}"

# 1. build.gradle.kts
python3 - "$VERSION" <<'PY'
import re, sys, pathlib
target = sys.argv[1]
p = pathlib.Path("build.gradle.kts")
text = p.read_text()
new, n = re.subn(r'(?m)^(\s*version\s*=\s*")[^"]+(")', rf'\g<1>{target}\g<2>', text, count=1)
if n == 0:
    raise SystemExit("Could not find  version = \"...\"  line in build.gradle.kts")
p.write_text(new)
PY
echo "  build.gradle.kts            -> ${VERSION}"

# 2. centsible-ui/package.json
python3 - "$VERSION" <<'PY'
import re, sys, pathlib
target = sys.argv[1]
p = pathlib.Path("centsible-ui/package.json")
text = p.read_text()
if re.search(r'"version"\s*:\s*"', text):
    new, _ = re.subn(r'("version"\s*:\s*")[^"]+(")', rf'\g<1>{target}\g<2>', text, count=1)
else:
    # Insert "version" right after "name".
    new, n = re.subn(
        r'("name"\s*:\s*"[^"]+",)\n',
        rf'\g<1>\n  "version": "{target}",\n',
        text,
        count=1,
    )
    if n == 0:
        # Fallback: inject right after the opening brace.
        new = re.sub(r'^\{\n', '{\n  "version": "%s",\n' % target, text, count=1)
p.write_text(new)
PY
echo "  centsible-ui/package.json -> ${VERSION}"

# 3. DB migration that syncs system_information.
MIGRATIONS_DIR="centsible-db/migrations"
LAST_NUM="$(ls "${MIGRATIONS_DIR}" | grep -E '^[0-9]+_' | sed -E 's/^([0-9]+)_.*/\1/' | sort -n | tail -1)"
NEXT_NUM="$(printf "%02d" "$((10#${LAST_NUM} + 1))")"
SLUG="$(echo "${VERSION}" | tr '.-' '__')"
MIGRATION_FILE="${MIGRATIONS_DIR}/${NEXT_NUM}_SetVersion_${SLUG}.sql"

cat > "${MIGRATION_FILE}" <<SQL
-- Release v${VERSION}: keep system_information aligned with the running build,
-- so /api/system and the About page report the correct version.
-- Generated by scripts/release.sh.
UPDATE system_information
SET version     = '${VERSION}',
    released_at = CURRENT_DATE,
    modified_at = now()
WHERE id = 1;
SQL
echo "  ${MIGRATION_FILE}"

# 4. Commit + tag.
git add build.gradle.kts centsible-ui/package.json "${MIGRATION_FILE}"
git commit -m "chore(release): v${VERSION}

Cut release v${VERSION} (from ${CURRENT_VERSION}).

  - build.gradle.kts                ${CURRENT_VERSION} -> ${VERSION}
  - centsible-ui/package.json  ${VERSION}
  - ${MIGRATION_FILE}
    syncs system_information.version + released_at on next deploy."

git tag -a "${TAG}" -m "Centsible v${VERSION}"

cat <<EOF

Release v${VERSION} prepared on branch ${BRANCH}.

Next steps:
  1. Update CHANGELOG.md with notes for v${VERSION}, then:
       git add CHANGELOG.md && git commit --amend --no-edit
       git tag -f ${TAG} -a -m "Centsible v${VERSION}"
  2. Push branch and tag:
       git push -u origin ${BRANCH}
       git push origin ${TAG}
  3. Open PR ${BRANCH} -> main.
EOF
